version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mymongo
    ports:
      - 8081:36565
    volumes:
      - /home/fred/mydatadock:/data/db
    command: --port 36565 

networks:
  default:
    external:
      name: mynet
